#ifndef _NSPIDER_CONFIG_H_INCLUDED_
#define _NSPIDER_CONFIG_H_INCLUDED_

#ifndef NSPR_HAVE_OS_LINUX
#define NSPR_HAVE_OS_LINUX  1
#endif

#ifndef NSPR_EVENT_FDS_SIZE
#define NSPR_EVENT_FDS_SIZE  1024
#endif

#ifndef NSPR_HAVE_DEBUG
#define NSPR_HAVE_DEBUG 1
#endif

#endif /* _NSPIDER_CONFIG_H_INCLUDED_ */
